// app/api/ai/generate-image/route.ts

import { NextResponse } from 'next/server';

// Simulating an AI image generation function (Replace with real API call)
const generateAIImage = async (prompt: string): Promise<string> => {
  try {
    // Replace this mock logic with a real API call (e.g., OpenAI's DALL·E API or similar)
    
    // Example using OpenAI API with DALL·E (this is just an example, ensure you have your API key configured properly)
    const response = await fetch("https://api.openai.com/v1/images/generations", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${process.env.OPENAI_API_KEY}`, // Make sure you add your OpenAI API key here
      },
      body: JSON.stringify({
        prompt: prompt,
        n: 1,
        size: "1024x1024", // You can adjust the size depending on your needs
      }),
    });

    const data = await response.json();
    if (data?.data && data.data[0]?.url) {
      return data.data[0].url;  // Return the image URL generated by DALL·E
    } else {
      throw new Error("Failed to generate image");
    }
  } catch (error) {
    console.error("Error generating image:", error);
    throw new Error("Failed to generate image");  // This error will be caught below
  }
};

// API route for generating an image based on a prompt
export async function POST(req: Request) {
  try {
    const { prompt } = await req.json();  // Extract prompt from request body

    if (!prompt) {
      return NextResponse.json({ error: "No prompt provided" }, { status: 400 });
    }

    // Generate image URL
    const generatedImageUrl = await generateAIImage(prompt);

    return NextResponse.json({ imageUrl: generatedImageUrl });
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: "Failed to generate image" }, { status: 500 });
  }
}
